services:
  - type: web
    name: n8n
    env: docker
    image: n8nio/n8n:latest
    plan: free
    region: ohio
    envVars:
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n
          property: hostport
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: SenhaForte123
